### PR TITLE
add a few things, make more functional

### PR DESCRIPTION
**Pull request by mzikherman**
Hi!

Here's a few updates that seemed to make things a bit more functional. The buttons only show the correct 'state' (if you are logged in, going to home page shouldn't show you a login button, etc.), you can view your list of favorites and add one, etc. It validates that you've already favorited that place. That kind of thing!

I hope this gives you some more ideas and things to add.

### CODE REVIEW

**Comment by Elronia** [comment]
Hello!

Thank you so much! It's a lot of changes! I didn't expect you to actually
write so much code! Thanks a lot! I know I am missing a lot in my
controllers and views. I would like to make those changes myself in VScode
to get more comfortable with coding. I noticed that you added  one
migration to the favorites table. I think I am not familiar with how to run
migrations with uniqueness, it's something new. I thought we can add
validations in the models itself. I am at the beginner's stage. How did the
command look like? rails g migration add_unique_index_to_favorites any data
type here? I also think that I have a problem validating the email. I am
using a gem for it. What would you recommend for it? Any advice would be
greatly appreciated. If I do a pull request will it be viewable by my
instructors?

Thank you,
Katherine

пн, 7 сент. 2020 г. в 16:19, Matt Zikherman <notifications@github.com>:

**Comment by Elronia** [comment]
What if I just try to repeat your changes myself? And I should probably let
the user see all the categories, click on them and see all the places for
the specific category and add them to favorites? What would you recommend
for seeding data? Faker for users? CSV file will probably give loots of
information. Do you think it will be hard to find API for NYC parks,
museums, etc. It probably requires a lot of time. I never worked with CSV
or API before.

Thank you,
Katherine

пн, 7 сент. 2020 г. в 16:53, Ekaterina Zarudnaya <zar.catherine@gmail.com>:

**Comment by mzikherman** [comment]
Yea, adding the migration for a unique constraint is the same as any other
one: rails g migration ..., I then just typed in that one line manually. I
think it makes sense: you probably can only favorite a place one time.

You can do a model validation, and even a validation on the front-end.
Doing a constraint at the database level (via migration), is the strongest
way you can do it. Many times it's a good idea to do it a 'weaker' way
(model validation, front-end), but also do it in the database if possible.

For email validation, I would use the email_validator gem.

Yea, on the public repo, all activity is viewable by anyone.

**Comment by mzikherman** [comment]
Up to you! I was sort of thinking the main 'page' in the app can be the
user's show page ('profile', whatever), where you can see all of the user's
info. Then, maybe each section has a link to 'Add new...', plus removing
them.

In terms of seeding data, I honestly rarely do that, so I don't have a
great suggestion there. For the data, you mean you need a set of NYC
places? I would search around and maybe import that as a one-time thing, I
don't know off hand where to get that.

When searching for that data, using the term "open data" can return a lot
of free datasets/CSVs/exports that might have data. I searched for 'nyc
parks open data' and this was the first link:
https://data.cityofnewyork.us/City-Government/ARCHIVED-Parks-Properties/k2ya-ucmv
.
It looks like you can basically export a CSV and get a list of names, for
example.

**Pull request merged**
